### I don't know a damn thing about database. So the purpose of this notebook is to get familiar with databases.

In [1]:
# importing packages
import os
import sys
sys.path.append("..")

import pandas as pd

import psycopg2
from sqlalchemy import create_engine
from urllib.parse import quote_plus



# configuration
_db_meta = {
    "HOST":"150.230.113.32",
    "PORT":"8899",
    "USER": "yima",
    "PASSWORD": "yima@09012024",
    "DB_TABLES": {
        "rss_embedding": "news_2024",
        "rss_reader": None,
    },
}


# get dataframe helper
def get_df(db_name):
    assert db_name in _db_meta["DB_TABLES"], f"?"

    encoded_password = quote_plus(_db_meta["PASSWORD"])
    db_url = f"postgresql://{_db_meta['USER']}:{encoded_password}@{_db_meta['HOST']}:{_db_meta['PORT']}/{db_name}"
    engine = create_engine(db_url)

    query = f"SELECT * FROM public.{_db_meta['DB_TABLES'][db_name]}"

    df = pd.read_sql(query, engine)

    return df

In [2]:
df = get_df("rss_embedding")

all the afore-steps done...

In [4]:
df.rename(columns={"publish_datetime": "datetime", "key_infomation": "key_information"}, inplace=True)

In [8]:
df.drop(columns=["id", "hash_code", "table_name", "origin_url", "embedding"], inplace=True)

In [9]:
df

,title,datetime,key_information
0,Analyst Predicts $20 Monthly Fee for Apple Int...,2024-08-08 14:20:01+00:00,"{""CARDINAL"": [""1"", ""2"", ""3"", ""18.1"", ""4"", ""18""..."
1,Lung cancer screenings save lives but are unfa...,2024-08-01 15:21:57+00:00,"{""CARDINAL"": [""Only about a quarter"", ""1"", ""at..."
2,Multiple people injured in stabbing in British...,2024-07-29 16:11:34+00:00,"{""CARDINAL"": [""eight"", ""two"", ""one"", ""about 95..."
3,‘I love my black job’: Simone Biles joins thos...,2024-08-02 16:45:27+00:00,"{""DATE"": [""June 27"", ""this week"", ""November"", ..."
4,Most birds avoid hurricanes. This species chas...,2024-07-17 04:14:06+00:00,"{""CARDINAL"": [""33"", ""six"", ""between 100 and 25..."
...,...,...,...
93732,Journalist told to pay damages for mocking Ita...,2024-07-18 23:07:35+00:00,"{""CARDINAL"": [""two"", ""only 1.2"", ""3"", ""9"", ""1...."
93733,Supreme Court keeps on hold laws seeking to li...,2024-07-01 19:42:00+00:00,"{""CARDINAL"": [""between two"", ""904"", ""393-9801""..."
93734,"France Election 2024: Marine Le Pen, leader of...",2024-06-30 10:21:00+00:00,"{""CARDINAL"": [""24/7""], ""DATE"": [""2024"", ""just ..."
93735,Here's why Walgreens and CVS retail pharmacies...,2024-08-18 12:00:01+00:00,"{""CARDINAL"": [""nearly 700"", ""50""], ""GPE"": [""Lo..."
93736,Kremlin hails return of spies but says swap wo...,2024-08-02 13:40:48+00:00,"{""DATE"": [""Friday""], ""EVENT"": [""the Cold War""]..."